â”€â”€ [1mAttaching packages[22m â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse 1.2.1 â”€â”€
[32mâœ”[39m [34mggplot2[39m 3.2.1     [32mâœ”[39m [34mpurrr  [39m 0.3.3
[32mâœ”[39m [34mtibble [39m 2.1.3     [32mâœ”[39m [34mdplyr  [39m 0.8.3
[32mâœ”[39m [34mtidyr  [39m 1.0.0     [32mâœ”[39m [34mstringr[39m 1.4.0
[32mâœ”[39m [34mreadr  [39m 1.3.1     [32mâœ”[39m [34mforcats[39m 0.4.0
â”€â”€ [1mConflicts[22m â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse_conflicts() â”€â”€
[31mâœ–[39m [34mdplyr[39m::[32mfilter()[39m masks [34mstats[39m::filter()
[31mâœ–[39m [34mdplyr[39m::[32mlag()[39m    masks [34mstats[39m::lag()
Preparing to deploy application...DONE
Uploading bundle for application: 1625713...DONE
Deploying bundle: 2705612 for application: 1625713 ...
Waiting for task: 680339387
  building: Parsing manifest
  building: Building image: 2953587
  building: Installing system dependencies
  building: Fetching packages
  building: Installing packages
  building: Installing files
  building: Pushing image: 2953587
  deploying: Starting instances
  terminating: Stopping old instances
Application successfully deployed to https://braydentang1.shinyapps.io/excaus_forecast/
â”€â”€ Attaching packages â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse 1.2.1 â”€â”€
âœ” ggplot2 3.2.1     âœ” purrr   0.3.3
âœ” tibble  2.1.3     âœ” dplyr   0.8.3
âœ” tidyr   1.0.0     âœ” stringr 1.4.0
âœ” readr   1.3.1     âœ” forcats 0.4.0
â”€â”€ Conflicts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse_conflicts() â”€â”€
âœ– dplyr::filter() masks stats::filter()
âœ– dplyr::lag()    masks stats::lag()
Error in gzfile(file, mode) : cannot open the connection
Calls: saveRDS -> gzfile
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file 'data/rds/excaus.rds', probable reason 'No such file or directory'
Execution halted
â”€â”€ Attaching packages â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse 1.2.1 â”€â”€
âœ” ggplot2 3.2.1     âœ” purrr   0.3.3
âœ” tibble  2.1.3     âœ” dplyr   0.8.3
âœ” tidyr   1.0.0     âœ” stringr 1.4.0
âœ” readr   1.3.1     âœ” forcats 0.4.0
â”€â”€ Conflicts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse_conflicts() â”€â”€
âœ– dplyr::filter() masks stats::filter()
âœ– dplyr::lag()    masks stats::lag()
Error in gzfile(file, mode) : cannot open the connection
Calls: saveRDS -> gzfile
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file 'data/rds/excaus.rds', probable reason 'No such file or directory'
Execution halted
